# Markov Chains 

In [1]:
import numpy as np
import matplotlib.pyplot as plt

üí´ Imagine that your cat and yourself have a superpower: the power of teleportation üí´

üê± Your cat Emily is quite young and is discovering her superpower. 

She can use it only in three cities:
- üá´üá∑ Paris
- 🇬🇧 London
- üá©üá™ Berlin

And she can teleport herself from one city to the other only once per day!

üò± Since you've been focusing on the Data Science challenges, you've just realised that you don't know where she's gone.

üëâ However, based on some intuition, you "know" that:
- from Paris, she will:
    - stay in Paris tomorrow with probability 1/3
    - move to London with probability 1/3
    - move to Berlin with probability 1/3

- from London, she will:
    - move to Paris with probability 35%
    - stay in London with probability 35%
    - move to Berlin with probability 30%

- from Berlin, she will:
    - move to Paris with probability 15%
    - move to London with probability 20%
    - stay in Berlin tomorrow with probability 65%


## üê± 1) Modelling the cat's movement

### 1.1) Draft

✍️ Take a pen and a piece of paper to visualise Emily's moves.

<details>
   <summary>👀 Visual representation of this Markov Chain ( do it yourself first !)</summary>


</details>

### ✈️ 1.2) Transitions

We'll create for you the [`transition_matrix`](https://en.wikipedia.org/wiki/Stochastic_matrix) Q that represents these moves between `["paris", "london", "berlin"]`


If the probability of moving from `i` to `j` in one time step is $P(j|i) = P_{i,j}$, the transition matrix `Q` is given by using $P_{i,j}$ as the i-th row and j-th column element, e.g.,

$${\begin{bmatrix}P_{1,1}&P_{1,2}&\dots &P_{1,j}&\dots &P_{1,S}\\P_{2,1}&P_{2,2}&\dots &P_{2,j}&\dots &P_{2,S}\\\vdots &\vdots &\ddots &\vdots &\ddots &\vdots \\P_{i,1}&P_{i,2}&\dots &P_{i,j}&\dots &P_{i,S}\\\vdots &\vdots &\ddots &\vdots &\ddots &\vdots \\P_{S,1}&P_{S,2}&\dots &P_{S,j}&\dots &P_{S,S}\\\end{bmatrix}}$$

So for Emily, the transition matrix will be :

$${\begin{bmatrix}
P_{Paris \rightarrow Paris}&P_{Paris \rightarrow London} &P_{Paris \rightarrow Berlin}\\
P_{London \rightarrow Paris}&P_{London \rightarrow London}&P_{London \rightarrow Berlin}\\
P_{Berlin \rightarrow Paris}&P_{Berlin \rightarrow London}&P_{Berlin \rightarrow Berlin}\\
\end{bmatrix}}$$

In [2]:
# Display the array Q

Q = np.array([[1 / 3, 1 / 3, 1 / 3], [0.35, 0.35, 0.3], [0.15, 0.2, 0.65]])
Q

array([[0.33333333, 0.33333333, 0.33333333],
       [0.35      , 0.35      , 0.3       ],
       [0.15      , 0.2       , 0.65      ]])

Also called **`stochastic matrixes`**, these matrixes have a remarkable property: Each line is a **`probability vector`**, its coefficients sum up to 1 = 100%

üëâ Let's imagine Emily started in Paris **initially**  
We'll create an initial_position array (1 row  √ó  3 columns) storing those information

In [36]:
# Complete
initial_position = np.array([1, 0, 0])
initial_position

array([1, 0, 0])

‚ùì What the probability for Emily to be in paris/london/berlin in next step? Try to compute it, using dot products between
- some slices of `Q`
- and `initial_position`

In [37]:
print("Paris :", initial_position.dot(Q)[0])
print("London:", initial_position.dot(Q)[1])
print("Berlin:", initial_position.dot(Q)[2])

Paris : 0.3333333333333333
London: 0.3333333333333333
Berlin: 0.3333333333333333


ℹ️ Now, let's assume you don't know where your cat was last seen, but you have some initial guess: She's **initially**:
- in Paris with a probability equal to 30%
- in London with a probability equal to 40%
- in Berlin with a probability equal to 30%

‚ùì Create your (1,3) array of `initial_position`  

In [25]:
initial_position = np.array([0.3, 0.4, 0.3])
initial_position

array([0.3, 0.4, 0.3])

‚ùì Compute the $ (1,3) $ array of probabilities `day_1` of the cat being in each city on ***day 1*** with an elegant math formula ‚ùì



In [27]:
day_1 = initial_position.dot(Q)
day_1

array([0.285, 0.3  , 0.415])

‚ùì What is the probability that Emily will be in Paris on day 2 ? What about London and Berlin ‚ùì

In [29]:
day_2 = day_1.dot(Q)
print("Probability for Emily to be in Paris  on day 2:", day_2[0])
print("Probability for Emily to be in London on day 2:", day_2[1])
print("Probability for Emily to be in Berlin on day 2:", day_2[2])

Probability for Emily to be in Paris  on day 2: 0.26225
Probability for Emily to be in London on day 2: 0.283
Probability for Emily to be in Berlin on day 2: 0.45475


### ‚è≥ 1.3) Where is the cat *n* days later ? 

‚ùì Create a function `emily` which computes the probabilities of Emily being in Paris, Berlin and London after `n_days`‚ùì

* `Inputs` : `initial_position`, `transition_matrix` and `n_days`
* `Output` : probabilities of each city

In [30]:
def emily(initial_position, transition_matrix, n_days):
    # COMPLETE
    final_position = initial_position
    for i in range(n_days):
        final_position = final_position.dot(transition_matrix)
    return final_position

‚ùì So, where will Emily be in 100 days ‚ùì

In [31]:
emily(initial_position, Q, 100)

array([0.25093633, 0.27465668, 0.47440699])

### üìà 1.4) Visualising the probabilities overtime

‚ùì Plot the probabilities of being in each city over time

üòâ This last question is non-guided !

In [32]:
def emily_over_time(initial_position, transition_matrix, n_days):

    paris = []
    london = []
    berlin = []

    ## Computing the probabilities each day
    #YOUR CODE
    
    for i in range (n_days):
        prob_that_day = emily(initial_position, transition_matrix, i + 1)
        paris.append(prob_that_day[0])
        london.append(prob_that_day[1])
        berlin.append(prob_that_day[2])

    ## Visualing
    #YOUR CODE
    print(paris)
    print(london)
    print(berlin)
 

In [33]:
emily_over_time(initial_position, Q, 100)

[0.285, 0.26225, 0.2546791666666666, 0.25217451388888884, 0.2513459386574074, 0.2510718341242284, 0.2509811564258616, 0.25095115894685033, 0.2509412353519285, 0.2509379524848538, 0.2509368664654913, 0.2509365071947597, 0.2509363883428653, 0.2509363490249594, 0.25093633601803406, 0.25093633171515717, 0.250936330291704, 0.25093632982080527, 0.25093632966502527, 0.250936329613491, 0.2509363295964427, 0.2509363295908029, 0.2509363295889372, 0.25093632958831996, 0.2509363295881158, 0.25093632958804823, 0.25093632958802586, 0.2509363295880185, 0.250936329588016, 0.2509363295880152, 0.25093632958801493, 0.2509363295880148, 0.2509363295880148, 0.25093632958801476, 0.25093632958801476, 0.25093632958801476, 0.25093632958801476, 0.25093632958801476, 0.25093632958801476, 0.25093632958801476, 0.25093632958801476, 0.25093632958801476, 0.25093632958801476, 0.25093632958801476, 0.25093632958801476, 0.25093632958801476, 0.25093632958801476, 0.25093632958801476, 0.25093632958801476, 0.25093632958801476,

## ü•° 2) Takeaways

❤️ After `Emily in Paris`, we'll most likely have `Emily in Berlin` in the long run !

❗️ ***Not all the Markov Chains converge to a stable state ❗️*** Think about a hamster who lives between two states 0 and 1 and moves from one to the other with probability 1 each day ! 

üí° Did you know? 
- Google computes the probability that from one page, you click on other pages ! 
- Its secret algorithm is based on Markov Chains (and of course advanced refinements which made the founders billionaires...!)
- üìö `Google Search Engine` : [Analytics Vidhya article - Google Page Rank and Markov Chains](https://medium.com/analytics-vidhya/google-page-rank-and-markov-chains-d65717b98f9c)


🏁 Congratulations !

üíæ Do not forget to `save`your notebook

üòÅ No panic if Markov Chains are still not clear for you. This challenge was more like an introduction to this topic, however for Data Analyst and Junior Data Scientists or Dev IA , you won't need necessarily use it :) 

🥳 Consider that it was a good opportunity to manipulate tools from `Linear Algebra` such as `matrixes` and tools from `Probabilty Theory` such as `probability distributions` !